---
- name: "Post installation actions: Reindex"
  shell: >
    {{ magento2_install_path }}/bin/magento indexer:reindex

- name: "Post isntallation actions: Clear cache"
  shell: >
    {{ magento2_install_path }}/bin/magento cache:clean
